"""Report generation for ai-devex."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Template

from ai_devex.config import Config
from ai_devex.logger import LogFile
from ai_devex.scanner import GitScanner, ScannedCommit

REPORT_TEMPLATE = """# AI Development Report: {{ config.project_name }}

{% if config.description %}
{{ config.description }}
{% endif %}

{% if config.repo_url %}
Repository: <{{ config.repo_url }}>
{% endif %}

---

## Summary

| Metric | Value |
|--------|-------|
| Logged AI sessions | {{ total_entries }} |
| Unique tools used | {{ tool_names | length }} |
| AI-related commits found | {{ scanned_commits | length }} |

{% if tool_summary %}
### Tools Breakdown

| Tool | Sessions |
|------|----------|
{% for tool, count in tool_summary.items() %}
| {{ tool }} | {{ count }} |
{% endfor %}

{% endif %}
{% if tag_summary %}
### Tags Breakdown

| Tag | Sessions |
|-----|----------|
{% for tag, count in tag_summary.items() %}
| {{ tag }} | {{ count }} |
{% endfor %}

{% endif %}
{% if entries %}
## Logged Sessions

{% for entry in entries %}
### {{ entry.timestamp[:10] }}{% if entry.tags %} [{{ entry.tags | join(", ") }}]{% endif %}

**Description:** {{ entry.description }}

{% if entry.tools %}
**Tools:** {{ entry.tools | join(", ") }}
{% endif %}
{% if entry.files %}
**Files touched:**
{% for file in entry.files %}
- `{{ file }}`
{% endfor %}
{% endif %}
{% if entry.commit %}
**Commit:** `{{ entry.commit }}`
{% endif %}

---

{% endfor %}
{% endif %}
{% if scanned_commits %}
## AI-Related Commits from Git History

{% for commit in scanned_commits %}
### {{ commit.hash }} - {{ commit.date[:10] }}

**Subject:** {{ commit.subject }}

{% if commit.body %}
**Body:**

{{ commit.body }}

{% endif %}
**Matched keywords:** {{ commit.matched_keywords | join(", ") }}

---

{% endfor %}
{% endif %}
*Generated by ai-devex v{{ version }}*
"""


def generate_report(
    config: Config,
    log_file: LogFile,
    scanner: GitScanner | None = None,
    max_commits: int = 50,
) -> str:
    """Generate a markdown report from logs and optional git history."""
    entries = log_file.read_all()
    tool_summary = log_file.tool_summary()
    tag_summary = log_file.tag_summary()

    scanned_commits: list[ScannedCommit] = []
    if scanner is not None and scanner.is_git_repo():
        scanned_commits = scanner.scan_commits(max_count=max_commits)

    template = Template(REPORT_TEMPLATE, trim_blocks=True, lstrip_blocks=True)
    return template.render(
        config=config,
        entries=entries,
        total_entries=len(entries),
        tool_summary=tool_summary,
        tag_summary=tag_summary,
        tool_names=list(tool_summary.keys()),
        scanned_commits=scanned_commits,
        version="0.2.0",
    )


def write_report(path: Path | str, content: str) -> None:
    """Write the report to disk."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
