"""Git history scanner for AI-related commit patterns."""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

AI_KEYWORDS = [
    "claude",
    "cursor",
    "copilot",
    "chatgpt",
    "gpt-4",
    "gpt4",
    "gpt-3",
    "gpt3",
    "openai",
    "anthropic",
    "ai-assisted",
    "ai assisted",
    "ai-generated",
    "ai generated",
    "generated by ai",
    "with claude",
    "with cursor",
    "with copilot",
    "via claude",
    "via cursor",
    "via copilot",
    "using claude",
    "using cursor",
    "using copilot",
]

COMMIT_PATTERN = re.compile(
    r"^(?P<hash>[a-f0-9]+)\x00(?P<date>[^\x00]+)\x00(?P<subject>[^\x00]+)\x00(?P<body>.*)$",
    re.MULTILINE | re.DOTALL,
)


@dataclass
class ScannedCommit:
    """A git commit that potentially involved AI assistance."""

    hash: str
    date: str
    subject: str
    body: str
    matched_keywords: list[str]

    @property
    def full_message(self) -> str:
        """Return the full commit message."""
        if self.body:
            return f"{self.subject}\n\n{self.body}"
        return self.subject


class GitScanner:
    """Scans git history for AI-related commits."""

    def __init__(self, repo_root: Path | str) -> None:
        self.repo_root = Path(repo_root)

    def _run_git(self, args: list[str]) -> str:
        """Run a git command and return stdout."""
        result = subprocess.run(
            ["git", *args],
            cwd=self.repo_root,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout

    def scan_commits(self, max_count: int = 100) -> list[ScannedCommit]:
        """Scan recent commits for AI-related keywords."""
        log_format = "%H%x00%ad%x00%s%x00%b%x00--END--\n"
        output = self._run_git(
            [
                "log",
                f"--max-count={max_count}",
                f"--format={log_format}",
                "--date=iso-strict",
            ]
        )

        matches: list[ScannedCommit] = []
        for raw in output.split("--END--"):
            raw = raw.strip()
            if not raw:
                continue

            m = COMMIT_PATTERN.match(raw)
            if not m:
                continue

            subject = m.group("subject").lower()
            body = m.group("body").lower()
            combined = f"{subject}\n{body}"

            found_keywords = [kw for kw in AI_KEYWORDS if kw.lower() in combined]
            if found_keywords:
                matches.append(
                    ScannedCommit(
                        hash=m.group("hash")[:7],
                        date=m.group("date"),
                        subject=m.group("subject"),
                        body=m.group("body").strip(),
                        matched_keywords=found_keywords,
                    )
                )

        return matches

    def is_git_repo(self) -> bool:
        """Check if the current directory is inside a git repository."""
        try:
            self._run_git(["rev-parse", "--git-dir"])
            return True
        except subprocess.CalledProcessError:
            return False

    def get_repo_url(self) -> str:
        """Try to get the remote origin URL."""
        try:
            return self._run_git(["remote", "get-url", "origin"]).strip()
        except subprocess.CalledProcessError:
            return ""
